List<Map<String, String>> countries = [
  {"country": "Cyprus", "ddi": "+357", "flag": "cy"},
  {"country": "Eritrea", "ddi": "+291", "flag": "er"},
  {"country": "Liberia", "ddi": "+231", "flag": "lr"},
  {"country": "Bermuda", "ddi": "+1", "flag": "bm"},
  {"country": "Vatican City", "ddi": "+1", "flag": "va"},
  {"country": "Cook Islands", "ddi": "+682", "flag": "ck"},
  {"country": "Somalia", "ddi": "+252", "flag": "so"},
  {"country": "Zambia", "ddi": "+260", "flag": "zm"},
  {"country": "Venezuela", "ddi": "+58", "flag": "ve"},
  {"country": "Turkmenistan", "ddi": "+993", "flag": "tm"},
  {"country": "Albania", "ddi": "+355", "flag": "al"},
  {"country": "Croatia", "ddi": "+385", "flag": "hr"},
  {"country": "United Kingdom", "ddi": "+44", "flag": "gb"},
  {"country": "Sudan", "ddi": "+249", "flag": "sd"},
  {"country": "Timor-Leste", "ddi": "+670", "flag": "tl"},
  {"country": "Republic of the Congo", "ddi": "+242", "flag": "cg"},
  {"country": "Azerbaijan", "ddi": "+994", "flag": "az"},
  {"country": "Kenya", "ddi": "+254", "flag": "ke"},
  {"country": "American Samoa", "ddi": "+1", "flag": "as"},
  {"country": "Ivory Coast", "ddi": "+225", "flag": "ci"},
  {"country": "Senegal", "ddi": "+221", "flag": "sn"},
  {"country": "Vietnam", "ddi": "+84", "flag": "vn"},
  {"country": "El Salvador", "ddi": "+503", "flag": "sv"},
  {"country": "Afghanistan", "ddi": "+93", "flag": "Flag_of_the_Taliban"},
  {"country": "Saint Martin", "ddi": "+590", "flag": "mf"},
  {"country": "Latvia", "ddi": "+371", "flag": "lv"},
  {"country": "Guatemala", "ddi": "+502", "flag": "gt"},
  {"country": "Kuwait", "ddi": "+965", "flag": "kw"},
  {"country": "São Tomé and Príncipe", "ddi": "+239", "flag": "st"},
  {"country": "Kyrgyzstan", "ddi": "+996", "flag": "kg"},
  {"country": "Poland", "ddi": "+48", "flag": "pl"},
  {"country": "Guam", "ddi": "+1", "flag": "gu"},
  {"country": "Ghana", "ddi": "+233", "flag": "gh"},
  {"country": "Lithuania", "ddi": "+370", "flag": "lt"},
  {"country": "Armenia", "ddi": "+374", "flag": "am"},
  {"country": "Jersey", "ddi": "+44", "flag": "je"},
  {"country": "Grenada", "ddi": "+1", "flag": "gd"},
  {"country": "Tajikistan", "ddi": "+992", "flag": "tj"},
  {"country": "Ethiopia", "ddi": "+251", "flag": "et"},
  {"country": "Western Sahara", "ddi": "+1", "flag": "eh"},
  {"country": "Morocco", "ddi": "+212", "flag": "ma"},
  {"country": "Puerto Rico", "ddi": "+1", "flag": "pr"},
  {"country": "Christmas Island", "ddi": "+61", "flag": "cx"},
  {"country": "New Zealand", "ddi": "+64", "flag": "nz"},
  {"country": "Brunei", "ddi": "+673", "flag": "bn"},
  {"country": "French Guiana", "ddi": "+594", "flag": "gf"},
  {"country": "Niue", "ddi": "+683", "flag": "nu"},
  {"country": "Romania", "ddi": "+40", "flag": "ro"},
  {"country": "Svalbard and Jan Mayen", "ddi": "+1", "flag": "sj"},
  {"country": "Belarus", "ddi": "+375", "flag": "by"},
  {"country": "Panama", "ddi": "+507", "flag": "pa"},
  {"country": "Cameroon", "ddi": "+237", "flag": "cm"},
  {"country": "Czechia", "ddi": "+420", "flag": "cz"},
  {"country": "Saint Barthélemy", "ddi": "+590", "flag": "bl"},
  {"country": "Greece", "ddi": "+30", "flag": "gr"},
  {"country": "Mali", "ddi": "+223", "flag": "ml"},
  {"country": "Martinique", "ddi": "+596", "flag": "mq"},
  {"country": "France", "ddi": "+33", "flag": "fr"},
  {"country": "Pakistan", "ddi": "+92", "flag": "pk"},
  {"country": "Peru", "ddi": "+51", "flag": "pe"},
  {"country": "Barbados", "ddi": "+1", "flag": "bb"},
  {"country": "Greenland", "ddi": "+299", "flag": "gl"},
  {"country": "Saint Pierre and Miquelon", "ddi": "+508", "flag": "pm"},
  {"country": "Chad", "ddi": "+235", "flag": "td"},
  {"country": "Hungary", "ddi": "+36", "flag": "hu"},
  {"country": "Comoros", "ddi": "+269", "flag": "km"},
  {"country": "Bangladesh", "ddi": "+880", "flag": "bd"},
  {"country": "Tokelau", "ddi": "+690", "flag": "tk"},
  {"country": "Fiji", "ddi": "+679", "flag": "fj"},
  {"country": "China", "ddi": "+86", "flag": "cn"},
  {"country": "Colombia", "ddi": "+57", "flag": "co"},
  {"country": "British Virgin Islands", "ddi": "+1", "flag": "vg"},
  {"country": "Algeria", "ddi": "+213", "flag": "dz"},
  {"country": "Maldives", "ddi": "+960", "flag": "mv"},
  {"country": "Malaysia", "ddi": "+60", "flag": "my"},
  {"country": "Cayman Islands", "ddi": "+1", "flag": "ky"},
  {"country": "Spain", "ddi": "+34", "flag": "es"},
  {"country": "Ireland", "ddi": "+353", "flag": "ie"},
  {"country": "Estonia", "ddi": "+372", "flag": "ee"},
  {"country": "Paraguay", "ddi": "+595", "flag": "py"},
  {"country": "Uruguay", "ddi": "+598", "flag": "uy"},
  {"country": "South Africa", "ddi": "+27", "flag": "za"},
  {"country": "Saint Lucia", "ddi": "+1", "flag": "lc"},
  {"country": "Vanuatu", "ddi": "+678", "flag": "vu"},
  {"country": "Finland", "ddi": "+358", "flag": "fi"},
  {"country": "Sweden", "ddi": "+46", "flag": "se"},
  {"country": "British Indian Ocean Territory", "ddi": "+246", "flag": "io"},
  {"country": "Lebanon", "ddi": "+961", "flag": "lb"},
  {"country": "United States", "ddi": "+1", "flag": "us"},
  {"country": "Chile", "ddi": "+56", "flag": "cl"},
  {"country": "Norfolk Island", "ddi": "+672", "flag": "nf"},
  {"country": "Montserrat", "ddi": "+1", "flag": "ms"},
  {"country": "Australia", "ddi": "+61", "flag": "au"},
  {"country": "Belize", "ddi": "+501", "flag": "bz"},
  {"country": "Guyana", "ddi": "+592", "flag": "gy"},
  {"country": "Mongolia", "ddi": "+976", "flag": "mn"},
  {"country": "Tuvalu", "ddi": "+688", "flag": "tv"},
  {"country": "Dominican Republic", "ddi": "+1", "flag": "do"},
  {"country": "Equatorial Guinea", "ddi": "+240", "flag": "gq"},
  {"country": "Saint Kitts and Nevis", "ddi": "+1", "flag": "kn"},
  {"country": "Bolivia", "ddi": "+591", "flag": "bo"},
  {"country": "Nepal", "ddi": "+977", "flag": "np"},
  {
    "country": "French Southern and Antarctic Lands",
    "ddi": "+262",
    "flag": "tf"
  },
  {"country": "Taiwan", "ddi": "+886", "flag": "tw"},
  {"country": "Benin", "ddi": "+229", "flag": "bj"},
  {"country": "Bulgaria", "ddi": "+359", "flag": "bg"},
  {"country": "Moldova", "ddi": "+373", "flag": "md"},
  {"country": "Isle of Man", "ddi": "+44", "flag": "im"},
  {"country": "Bhutan", "ddi": "+975", "flag": "bt"},
  {"country": "Cambodia", "ddi": "+855", "flag": "kh"},
  {"country": "Antigua and Barbuda", "ddi": "+1", "flag": "ag"},
  {"country": "Haiti", "ddi": "+509", "flag": "ht"},
  {"country": "Cape Verde", "ddi": "+238", "flag": "cv"},
  {"country": "Georgia", "ddi": "+995", "flag": "ge"},
  {"country": "Burundi", "ddi": "+257", "flag": "bi"},
  {"country": "Bahamas", "ddi": "+1", "flag": "bs"},
  {"country": "Mauritius", "ddi": "+230", "flag": "mu"},
  {"country": "Libya", "ddi": "+218", "flag": "ly"},
  {"country": "Malawi", "ddi": "+265", "flag": "mw"},
  {"country": "Mexico", "ddi": "+52", "flag": "mx"},
  {"country": "Eswatini", "ddi": "+268", "flag": "sz"},
  {"country": "Papua New Guinea", "ddi": "+675", "flag": "pg"},
  {"country": "Dominica", "ddi": "+1", "flag": "dm"},
  {"country": "Liechtenstein", "ddi": "+423", "flag": "li"},
  {"country": "Russia", "ddi": "+73", "flag": "ru"},
  {"country": "Israel", "ddi": "+972", "flag": "il"},
  {"country": "Singapore", "ddi": "+65", "flag": "sg"},
  {"country": "Uganda", "ddi": "+256", "flag": "ug"},
  {"country": "Slovakia", "ddi": "+421", "flag": "sk"},
  {"country": "Tonga", "ddi": "+676", "flag": "to"},
  {"country": "United Arab Emirates", "ddi": "+971", "flag": "ae"},
  {"country": "Mayotte", "ddi": "+262", "flag": "yt"},
  {"country": "Suriname", "ddi": "+597", "flag": "sr"},
  {"country": "Uzbekistan", "ddi": "+998", "flag": "uz"},
  {"country": "Saudi Arabia", "ddi": "+966", "flag": "sa"},
  {"country": "Egypt", "ddi": "+20", "flag": "eg"},
  {"country": "Italy", "ddi": "+39", "flag": "it"},
  {"country": "Madagascar", "ddi": "+261", "flag": "mg"},
  {"country": "New Caledonia", "ddi": "+687", "flag": "nc"},
  {"country": "Canada", "ddi": "+1", "flag": "ca"},
  {"country": "United States Virgin Islands", "ddi": "+1", "flag": "vi"},
  {"country": "Marshall Islands", "ddi": "+692", "flag": "mh"},
  {"country": "Mauritania", "ddi": "+222", "flag": "mr"},
  {"country": "Gambia", "ddi": "+220", "flag": "gm"},
  {"country": "Trinidad and Tobago", "ddi": "+1", "flag": "tt"},
  {"country": "Seychelles", "ddi": "+248", "flag": "sc"},
  {"country": "Japan", "ddi": "+81", "flag": "jp"},
  {"country": "Brazil", "ddi": "+55", "flag": "br"},
  {"country": "Syria", "ddi": "+963", "flag": "sy"},
  {
    "country": "Saint Helena, Ascension and Tristan da Cunha",
    "ddi": "+290",
    "flag": "sh"
  },
  {"country": "Tanzania", "ddi": "+255", "flag": "tz"},
  {"country": "Andorra", "ddi": "+376", "flag": "ad"},
  {"country": "Iran", "ddi": "+98", "flag": "ir"},
  {"country": "Togo", "ddi": "+228", "flag": "tg"},
  {"country": "Malta", "ddi": "+356", "flag": "mt"},
  {"country": "South Korea", "ddi": "+82", "flag": "kr"},
  {"country": "Samoa", "ddi": "+685", "flag": "ws"},
  {"country": "Germany", "ddi": "+49", "flag": "de"},
  {"country": "Niger", "ddi": "+227", "flag": "ne"},
  {"country": "Bouvet Island", "ddi": "+47", "flag": "bv"},
  {"country": "Jamaica", "ddi": "+1", "flag": "jm"},
  {"country": "Nicaragua", "ddi": "+505", "flag": "ni"},
  {"country": "Guinea", "ddi": "+224", "flag": "gn"},
  {"country": "Anguilla", "ddi": "+1", "flag": "ai"},
  {"country": "Åland Islands", "ddi": "+1", "flag": "ax"},
  {"country": "Belgium", "ddi": "+32", "flag": "be"},
  {"country": "Portugal", "ddi": "+351", "flag": "pt"},
  {"country": "Denmark", "ddi": "+45", "flag": "dk"},
  {"country": "Philippines", "ddi": "+63", "flag": "ph"},
  {"country": "Wallis and Futuna", "ddi": "+681", "flag": "wf"},
  {"country": "Austria", "ddi": "+43", "flag": "at"},
  {"country": "Guinea-Bissau", "ddi": "+245", "flag": "gw"},
  {"country": "Monaco", "ddi": "+377", "flag": "mc"},
  {"country": "Namibia", "ddi": "+264", "flag": "na"},
  {
    "country": "United States Minor Outlying Islands",
    "ddi": "+268",
    "flag": "um"
  },
  {"country": "Costa Rica", "ddi": "+506", "flag": "cr"},
  {"country": "Bosnia and Herzegovina", "ddi": "+387", "flag": "ba"},
  {"country": "Macau", "ddi": "+853", "flag": "mo"},
  {"country": "Mozambique", "ddi": "+258", "flag": "mz"},
  {"country": "Réunion", "ddi": "+262", "flag": "re"},
  {"country": "Montenegro", "ddi": "+382", "flag": "me"},
  {"country": "North Korea", "ddi": "+850", "flag": "kp"},
  {"country": "Northern Mariana Islands", "ddi": "+1", "flag": "mp"},
  {"country": "Ukraine", "ddi": "+380", "flag": "ua"},
  {"country": "Iraq", "ddi": "+964", "flag": "iq"},
  {"country": "South Georgia", "ddi": "+500", "flag": "gs"},
  {"country": "Angola", "ddi": "+244", "flag": "ao"},
  {"country": "Sierra Leone", "ddi": "+232", "flag": "sl"},
  {"country": "Micronesia", "ddi": "+691", "flag": "fm"},
  {"country": "Cuba", "ddi": "+53", "flag": "cu"},
  {"country": "Turks and Caicos Islands", "ddi": "+1", "flag": "tc"},
  {"country": "Serbia", "ddi": "+381", "flag": "rs"},
  {"country": "Ecuador", "ddi": "+593", "flag": "ec"},
  {"country": "Faroe Islands", "ddi": "+298", "flag": "fo"},
  {"country": "Palestine", "ddi": "+970", "flag": "ps"},
  {"country": "Turkey", "ddi": "+90", "flag": "tr"},
  {"country": "Kiribati", "ddi": "+686", "flag": "ki"},
  {"country": "Kazakhstan", "ddi": "+76", "flag": "kz"},
  {"country": "Gibraltar", "ddi": "+350", "flag": "gi"},
  {"country": "Iceland", "ddi": "+354", "flag": "is"},
  {"country": "Palau", "ddi": "+680", "flag": "pw"},
  {"country": "Qatar", "ddi": "+974", "flag": "qa"},
  {"country": "Switzerland", "ddi": "+41", "flag": "ch"},
  {"country": "French Polynesia", "ddi": "+689", "flag": "pf"},
  {"country": "Pitcairn Islands", "ddi": "+64", "flag": "pn"},
  {"country": "Jordan", "ddi": "+962", "flag": "jo"},
  {"country": "Myanmar", "ddi": "+95", "flag": "mm"},
  {"country": "Thailand", "ddi": "+66", "flag": "th"},
  {"country": "Caribbean Netherlands", "ddi": "+599", "flag": "bq"},
  {"country": "Aruba", "ddi": "+297", "flag": "aw"},
  {"country": "Guadeloupe", "ddi": "+590", "flag": "gp"},
  {"country": "Nigeria", "ddi": "+234", "flag": "ng"},
  {"country": "Bahrain", "ddi": "+973", "flag": "bh"},
  {"country": "Laos", "ddi": "+856", "flag": "la"},
  {"country": "Cocos (Keeling) Islands", "ddi": "+61", "flag": "cc"},
  {"country": "Djibouti", "ddi": "+253", "flag": "dj"},
  {"country": "Solomon Islands", "ddi": "+677", "flag": "sb"},
  {"country": "India", "ddi": "+91", "flag": "in"},
  {"country": "San Marino", "ddi": "+378", "flag": "sm"},
  {"country": "Luxembourg", "ddi": "+352", "flag": "lu"},
  {"country": "Sint Maarten", "ddi": "+1", "flag": "sx"},
  {"country": "Falkland Islands", "ddi": "+500", "flag": "fk"},
  {"country": "Central African Republic", "ddi": "+236", "flag": "cf"},
  {"country": "Botswana", "ddi": "+267", "flag": "bw"},
  {"country": "Curaçao", "ddi": "+599", "flag": "cw"},
  {"country": "Guernsey", "ddi": "+44", "flag": "gg"},
  {"country": "Norway", "ddi": "+47", "flag": "no"},
  {"country": "Gabon", "ddi": "+241", "flag": "ga"},
  {"country": "Zimbabwe", "ddi": "+263", "flag": "zw"},
  {"country": "Lesotho", "ddi": "+266", "flag": "ls"},
  {"country": "Slovenia", "ddi": "+386", "flag": "si"},
  {"country": "Argentina", "ddi": "+54", "flag": "ar"},
  {"country": "Burkina Faso", "ddi": "+226", "flag": "bf"},
  {"country": "Yemen", "ddi": "+967", "flag": "ye"},
  {"country": "DR Congo", "ddi": "+243", "flag": "cd"},
  {"country": "Oman", "ddi": "+968", "flag": "om"},
  {"country": "Indonesia", "ddi": "+62", "flag": "id"},
  {"country": "Nauru", "ddi": "+674", "flag": "nr"},
  {"country": "Rwanda", "ddi": "+250", "flag": "rw"},
  {"country": "North Macedonia", "ddi": "+389", "flag": "mk"},
  {"country": "Kosovo", "ddi": "+383", "flag": "xk"},
  {"country": "Netherlands", "ddi": "+31", "flag": "nl"},
  {"country": "Tunisia", "ddi": "+216", "flag": "tn"},
  {"country": "South Sudan", "ddi": "+211", "flag": "ss"},
  {"country": "Honduras", "ddi": "+504", "flag": "hn"},
  {"country": "Saint Vincent and the Grenadines", "ddi": "+1", "flag": "vc"},
  {"country": "Sri Lanka", "ddi": "+94", "flag": "lk"},
  {"country": "Hong Kong", "ddi": "+852", "flag": "hk"}
];
